export const AUTH_USER = 'auth_user',  
             UNAUTH_USER = 'unauth_user',
             AUTH_ERROR = 'auth_error',
             FORGOT_PASSWORD_REQUEST = 'forgot_password_request',
             RESET_PASSWORD_REQUEST = 'reset_password_request',
             GET_ACCOUNT_DATA = 'get_account_data',
             SET_STATE_USER_DATA = "SET_STATE_USER_DATA",
             CLEAR_USER_DATA = "CLEAR_USER_DATA",
             ADD_VISITED_PAGE = "ADD_VISITED_PAGE";